useless changes
BlueBirdMC/BlueBird pull request #23
Opened 2022-07-19 19:20 UTC by andriycraft

Hi! im andriycraft
i do lots of useless changes to ur repo

2022-07-19 20:42 UTC, andriycraft commented
Log:
[INFO] Running tests
[INFO] Config validator

2022-07-19 20:43 UTC, andriycraft commented
Invalid config:
[23:40:43] INFO > Loading Server...
[23:40:43] INFO > Loading BlueBird.json
[23:40:43] INFO > Loading Lang.json
[23:40:43] INFO > This server is running BlueBird, v1.0.10
[23:40:43] INFO > BlueBird is distributed under GPLv3 License
[23:40:43] WARNING > [CONFIG ERROR] Your config is outdated!
[23:40:43] WARNING > [CONFIG ERROR] missing 'etc' category
[23:40:43] CRITICAL > Unable to start server.

2022-07-19 20:43 UTC, andriycraft commented
Valid config

2022-07-19 20:44 UTC, andriycraft commented
all tests have failed

2022-07-20 08:30 UTC, VaxPex commented
??????

2022-07-20 09:15 UTC, andriycraft commented
> ??????

?

2022-07-20 09:16 UTC, andriycraft commented
this is the biggest pr i ever made

2022-07-20 09:16 UTC, andriycraft commented
misclicked

2022-07-24 09:41 UTC, andriycraft commented
TODO:
[] Commands
[] Remove debug

2022-08-01 11:38 UTC, andriycraft commented
debugging this is pain

2022-08-01 17:52 UTC, andriycraft commented
WARNING: This pr is not ready to be merged

2022-08-06 19:32 UTC, andriycraft commented
@VaxPex how to read packet in bluebird?

2022-08-07 09:34 UTC, andriycraft commented
@VaxPex are you alive?

2022-08-08 20:35 UTC, andriycraft commented
it works

2022-08-08 20:36 UTC, andriycraft commented
@VaxPex please merge this pr and give me contributor role on discord

2022-08-09 08:30 UTC, VaxPex commented
> @VaxPex please merge this pr and give me contributor role on discord

fix the disconnection then

2022-08-09 08:31 UTC, andriycraft commented
> > @VaxPex please merge this pr and give me contributor role on discord
> 
> fix the disconnection then



> > @VaxPex please merge this pr and give me contributor role on discord
> 
> fix the disconnection then

What disconnection? It works

2022-08-09 08:34 UTC, VaxPex commented
foreach the cmds then cmdidkwhat.dispatch(handler.player, cmd.substring(1))

2022-08-09 15:51 UTC, MyrsujV2 commented
hi

2022-08-12 16:20 UTC, MyrsujV2 commented
does it work

2022-08-12 16:20 UTC, MyrsujV2 commented
or no

2022-08-12 16:21 UTC, MyrsujV2 commented
or yes

2022-08-12 16:21 UTC, MyrsujV2 commented
or no

2022-08-12 16:21 UTC, MyrsujV2 commented
or yes

2022-08-15 15:13 UTC, andriycraft commented
yes

2022-08-15 15:31 UTC, AnyBananaGAME commented
ok!

2022-08-15 15:31 UTC, AnyBananaGAME commented
https://tenor.com/view/deadserver-gif-22763122

2022-08-15 16:23 UTC, andriycraft commented
> https://tenor.com/view/deadserver-gif-22763122

no

2022-08-15 16:23 UTC, andriycraft commented
ik its rickroll

2022-08-17 13:13 UTC, andriycraft commented
@VaxPex it works
will u merge it

2022-08-17 13:13 UTC, andriycraft commented
?

2022-08-17 13:25 UTC, andriycraft commented
no vaxpex dont merge it

2022-08-17 13:25 UTC, andriycraft commented
it contains bugs

2022-08-29 12:33 UTC, MyrsujV2 commented
it works ig

2022-09-12 08:58 UTC, PiggyPlex approved these changes

2022-09-12 08:59 UTC, PiggyPlex reviewed
seems sensible

2022-09-12 09:00 UTC, PiggyPlex approved these changes

2022-09-12 09:00 UTC, PiggyPlex approved these changes

2022-09-12 09:00 UTC, PiggyPlex commented on src/Server.js
> +					"gamemode": ""
should we not set a default?

2022-09-12 09:02 UTC, PiggyPlex requested changes

2022-09-12 09:02 UTC, PiggyPlex commented on src/Server.js
> +		} catch (e) {
unused variable `e`. consider logging the error to the console or prefixing it with `_`.

2022-09-12 09:02 UTC, PiggyPlex commented on src/Server.js
> +		if (!this.bluebirdcfg.getNested("etc.gamemode")) {
should use a schema validator instead

2022-09-12 09:02 UTC, PiggyPlex approved these changes

2022-09-12 09:03 UTC, PiggyPlex approved these changes

2022-09-14 19:49 UTC, MyrsujV2 commented
@PiggyPlex You approved this pr 4 times

2022-09-21 14:29 UTC, VaxPex commented
😂

2022-09-21 16:47 UTC, AnyBananaGAME commented
If all of the kings had their queens on the throne
We would pop champagne and raise a toast
To all of the queens who are fighting alone
Baby, you're not dancin' on your own
Can't live without me, you wanna, but you can't, no, no, no
Think it's funny, but honey, can't run this show on your own
I can feel my body shake, there's only so much I can take
I'll show you how a real queen behaves, oh
No damsel in distress, don't need to save me
Once I start breathin' fire, you can't tame me
And you might think I'm weak without a sword
But if I had one, it'd be bigger than yours
If all of the kings had their queens on the throne
We would pop champagne and raise a toast
To all of the queens who are fighting alone
Baby, you're not dancin' on your own
Disobey me, then baby, it's off with your head
Gonna change it and make it a world you won't forget, oh-oh, oh
No damsel in distress, don't need to save me
Once I start breathin' fire, you can't tame me
And you might think I'm weak without a sword
But I'm stronger than I ever was before
If all of the kings had their queens on the throne
We would pop champagne and raise a toast
To all of the queens who are fighting alone
Baby, you're not dancin' on your own
In chess, the king can move one space at a time
But queens are free to go wherever they like
You get too close, you'll get a royalty high
So breathe it in to feel alive (alive)
If all of the kings had their queens on the throne
We would pop champagne and raise a toast
To all of the queens who are fighting alone
Baby, you're not dancin' on your own

2022-12-17 03:27 UTC, closed without merging