Stuff
BlueBirdMC/BlueBird pull request #29
Opened 2022-07-26 07:32 UTC by AnyBananaGAME

2022-07-27 10:56 UTC, Liqee431 commented
New kickcommand but there is ni kickcommand?

2022-07-27 10:57 UTC, andriycraft commented
There is…

2022-07-27 12:37 UTC, AnyBananaGAME commented
> New kickcommand but there is no kickcommand?

No, did not add any new KickCommand stuff... I just added "," at the end of new KickCommand()
Before: new KickCommand() 
After: new KickCommand(), 

If i did not add that it would cause an error and just crash.

2022-07-27 12:39 UTC, AnyBananaGAME commented
And there is a KickCommand, It's located in the default commands folder

2022-08-07 09:31 UTC, andriycraft requested changes

2022-08-07 09:31 UTC, andriycraft commented on start.bat
> +echo The server either CRASHED or was killed... Starting a force restart.
Or stopped

2022-09-12 08:57 UTC, PiggyPlex requested changes

2022-09-12 08:57 UTC, PiggyPlex commented on start.bat
> +echo The server either CRASHED or was killed... Starting a force restart.
should have a `goto main` statement to force restart

2022-09-12 08:57 UTC, PiggyPlex commented on start.bat
> +echo The server either CRASHED or was killed... Starting a force restart.
should have a `timeout /t 2 /nobreak > nul` to be consistent with `start.sh` script

2022-09-12 08:57 UTC, PiggyPlex commented on src/command/default/FakeMessageCommand.js
> +module.exports = FakeSayCommand;
is this really needed as a core command?

2022-09-12 09:16 UTC, AnyBananaGAME commented on src/command/default/FakeMessageCommand.js
> +module.exports = FakeSayCommand;
No, but can be used

2022-09-12 11:38 UTC, VaxPex commented
> > New kickcommand but there is no kickcommand?
> 
> No, I did not add any new KickCommand stuff... I just added "," at the end of `new KickCommand()` Before: `new KickCommand() ` After: `new KickCommand(), `
> 
> If i did not add that it would cause an error and just crash.

It wont

2022-09-12 11:57 UTC, andriycraft commented
vaxpex is alive

2022-09-12 11:57 UTC, andriycraft commented
> > > New kickcommand but there is no kickcommand?
> > 
> > 
> > No, I did not add any new KickCommand stuff... I just added "," at the end of `new KickCommand()` Before: `new KickCommand() ` After: `new KickCommand(), `
> > If i did not add that it would cause an error and just crash.
> 
> It wont

It will kick the Player that used this command

2022-09-12 11:59 UTC, AnyBananaGAME commented
Ye, gives server an error and crashes the player.

2022-09-20 17:11 UTC, PiggyPlex commented
https://github.com/BlueBirdMC/BlueBird/pull/29/files/bfe5025a772e425a7cd87f684aad76f6b6799b9d

2022-12-17 03:27 UTC, closed without merging