Better code, i guess
BlueBirdMC/BlueBird pull request #7
Opened 2022-06-11 12:53 UTC by andriycraft

i didnt test it yet, so do not merge

2022-06-11 13:06 UTC, andriycraft commented
done, i guess

2022-06-11 13:08 UTC, andriycraft commented
Changes:
[/kick] reason is now optional
[skins] Fixed invalid skin size even if it is valid
[general code] Fixed some bad code
[config] Kick messages are not configurable

2022-06-11 13:11 UTC, andriycraft commented on changelog.md
>  #### 1.0.8
typo*

2022-06-11 13:40 UTC, VaxPex commented
and the err_... make it an object

2022-06-12 02:17 UTC, ProtectorYT364 commented
what is err

2022-06-12 07:11 UTC, VaxPex commented
tthe config

2022-06-12 07:11 UTC, VaxPex commented
in

2022-06-12 07:38 UTC, andriycraft commented
> and the err_... make it an object

done, i guess

2022-06-12 07:54 UTC, VaxPex commented
fetch & pull then i will look at it

2022-06-12 07:55 UTC, andriycraft commented
Done

2022-06-12 07:58 UTC, VaxPex requested changes
the skin.js

2022-06-12 08:00 UTC, ProtectorYT364 commented on src/entity/Skin.js
> +        4102
Lol

2022-06-12 08:02 UTC, VaxPex approved these changes

2022-06-12 08:02 UTC, andriycraft commented
merge

2022-06-12 08:02 UTC, merged